/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

public class App {

	private List<String> input;

	private List<ID> hasExactlyTwo;
	private List<ID> hasExactlyThree;
	private Set<String> completeList;

	public App() {
		this.hasExactlyTwo = new ArrayList<>();
		this.hasExactlyThree = new ArrayList<>();
		this.input = ReadInput.getInput();
		this.completeList = new LinkedHashSet<>();
	}

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		App app = new App();
		System.out.println(app.getGreeting());
//        System.out.println(app.getInput());

		app.run();
		app.setCompleteList();
		System.out.println("Has two: " + app.hasExactlyTwo.size());
		System.out.println("Has three: " + app.hasExactlyThree.size());
		int sum = app.hasExactlyThree.size() * app.hasExactlyTwo.size();
		System.out.println("Checksum: " + sum);

		String uniqueID = app.findID();
		System.out.println("ID: " + uniqueID);

	}

	private void setCompleteList() {

		for (int i = 0; i < this.hasExactlyThree.size(); i++) {
			this.completeList.add(this.hasExactlyThree.get(i).getId());
		}
		for (int i = 0; i < this.hasExactlyTwo.size(); i++) {
			this.completeList.add(this.hasExactlyTwo.get(i).getId());
		}

	}

	private void run() {
		for (String s : getInput()) {
			ID id = new ID(s);

			if (id.isHasExactlyTwo())
				this.hasExactlyTwo.add(id);
			if (id.isHasExactlyThree())
				this.hasExactlyThree.add(id);
		}

	}

	public List<String> getInput() {
		return this.input;
	}

	private String findID() {
		String foundID = null;

		for (String id : this.completeList) {
			 foundID = IDFinder.checkID(id, this.completeList);
				if(foundID != null)
					break;
			
		}

		return foundID;
	}
}
