/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Before;
import org.junit.Test;

public class AppTest {
	
	private List<String> input;
	
	@Before
	public void setUpInput()
	{
		this.input = ReadInput.getInput();
	}
    
    @Test
    public void inputNotEmptyTest()
    {
    	
    	assertNotNull(input);
    	
    }

}
