/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App
{

	private static List<String> input = ReadInput.getInput();
	private static List<Coordinate> coordinates = getCoordinates();

	public static void main(String[] args)
	{

		System.out.printf("Part 1: %d", part1());
		System.out.println();
		System.out.printf("Part 2: %d", part2());

	}

	public static int part1()
	{
		Board board = new Board(coordinates);
		board.setShortestCoordinatesToPoints();

		return board.findBiggestPatch();
	}

	public static int part2()
	{
		Board board = new Board(coordinates);

		int points = board.getAllClosePoints();
		
		

		return points;
	}

	public static List<Coordinate> getCoordinates()
	{
		List<Coordinate> list = new ArrayList<>();

		int count = 0;
		for (String in : input)
		{
			String id = String.format("%02d", count);
			Integer[] coor = new Integer[2];
			String regex = "^(?<x>\\d+), (?<y>\\d+)$";
			Pattern p = Pattern.compile(regex);
			Matcher m = p.matcher(in);
			m.find();
			coor[0] = Integer.parseInt(m.group("x"));
			coor[1] = Integer.parseInt(m.group("y"));
			list.add(new Coordinate(coor, id));
			count++;
		}

		return list;
	}

}