/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import static org.junit.Assert.assertEquals;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.Test;

public class AppTest {

	@Test
	public void matchGuardIDTest()
	{
		String line = "[1518-11-21 23:56] Guard #1097 begins shift";
		
		String regex = ".*#(?<id>[0-9]+).*";
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(line);
		m.find();
		assertEquals("Inga matchningar", 1, m.groupCount());
		assertEquals("Fel match", 1097, Integer.parseInt(m.group("id")));
	}

	
	@Test
	public void matchTimeTest()
	{
		
		String line = "[1518-11-04 00:48] wakes up";
		
		String regex = ".*:(?<time>[0-9]+)\\].*";
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(line);
		m.find();
		assertEquals("Inga matchningar", 1, m.groupCount());
		assertEquals("Fel match", 48, Integer.parseInt(m.group("time")));
		
	}

}
