/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import java.io.IOException;
import java.util.List;

public class App
{

	private static List<String> input = ReadInput.getInput();
	private static String in = input.get(0);

	public static void main(String[] args) throws IOException
	{
		System.out.println("Part 1:  " + part1(in).length());
		System.out.println("Part 2:  " + part2(in));
	}

	public static String part1(String in)
	{

		boolean tabort = true;
		while (tabort)
		{
			for (int i = 0; i < in.length() - 1; i++)
			{
				tabort = false;
				char char1 = in.charAt(i);
				char char2 = in.charAt(i + 1);

				boolean ch1isUpper = Character.isUpperCase(char1);
				boolean ch2isUpper = Character.isUpperCase(char2);

				if ((ch1isUpper && !ch2isUpper) || (!ch1isUpper && ch2isUpper))
				{
					if (Character.toLowerCase(char1) == Character.toLowerCase(char2))
					{
						in = in.substring(0, i) + in.substring(i + 2, in.length());
						tabort = true;
						break;
					}
				}

			}

		}
		return in;
	}

	public static String part2(String in)
	{
		int shortest = Integer.MAX_VALUE;
		char[] alphabet = "abcdefghijklmnopqrstuvwxyz".toCharArray();
		for (char c : alphabet)
		{
			StringBuilder str = new StringBuilder();
			for (int i = 0; i < in.length(); i++)
			{
				if (Character.toLowerCase(in.charAt(i)) != c)
				{
					str.append(in.charAt(i));
				}
			}
			int result = part1(str.toString()).length();
			if (result < shortest)
				shortest = result;

		}

		return "" + shortest;

	}

}